name: scp copy folder to remote via SSH

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          #key: ${{ secrets.KEY }}
          #port: ${{ secrets.PORT }}
          source: "deploy.tar"
          target: "/home/xpalinka/public_html/SWI2-autoservis"
