name: scp copy folder to remote via SSH
on: [push, pull_request, create]
jobs:
  deployOnDev:
    name: Deploy on dev
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: rm -rf /home/xpalinka/public_html/SWI2-autoservis/test && mkdir /home/xpalinka/public_html/SWI2-autoservis/test && cd /home/xpalinka/public_html/SWI2-autoservis/test && [ -d SWI2-autoserivs ] && git -C SWI2-autoserivs/ pull || git clone https://github.com/xpalinka/SWI2-autoserivs.git
  testOnDev:
    needs: deployOnDev
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /home/xpalinka/public_html/SWI2-autoservis/test/SWI2-autoserivs/ && chmod u=rwx test.sh && ./test.sh
  testUI:
    needs: testOnDev
    name: UI tests
    runs-on: ubuntu-latest
    steps:
    - name: setup cypress
      run: sudo apt-get install npm libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - run: npm install cypress --save-dev
    - run: ./node_modules/.bin/cypress run
    - name: Checkout code
      uses: actions/checkout@v2
    - run: ls -la
    - run: cd SWI2-autoserivs
  deployOnProduction:
    if: github.ref == 'refs/heads/master'
    needs: testOnDev
    name: Deploy on production
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /home/xpalinka/public_html/SWI2-autoservis && [ -d SWI2-autoserivs ] && git -C SWI2-autoserivs/ pull || git clone https://github.com/xpalinka/SWI2-autoserivs.git

